add_requires("fmt", "openssl", "glog", "cryptopp", "liburing")
add_requires("boost[asio,beast,url,json,system,program_options,multiprecision,pfr,math,chrono,filesystem,serialization,thread]")
add_rules("plugin.compile_commands.autoupdate", {outputdir = "build/"})
set_languages("c++23")

target("BitCoinTrader")
    set_kind("binary")
    add_includedirs("market/", "common/http", "common/utils", "config", "record")
    add_includedirs("service", "notice")
    add_files("market/**/*.cpp")
    add_files("common/**/*.cpp")
    add_files("service/**/*.cpp")
    add_files("notice/**/*.cpp")
    add_files("*.cpp")
    add_files("record/*.cpp")
    add_packages("fmt", "openssl", "glog", "cryptopp", "liburing")
    add_packages("boost")
    add_defines("BOOST_ASIO_HAS_IO_URING", "BOOST_ASIO_HAS_FILE")
    set_toolset("cxx", "clang")
    set_toolset("ld", "clang++")
