name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 当推送v开头的tag时触发

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # ✅ 关键权限设置必须正确
      packages: read    # ⚠️ 如果使用GitHub Packages可能需要
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # 新增缓存步骤（必须放在xmake安装前）
      - name: Cache Xmake Packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.xmake
            ~/.xmake/packages
          key: ${{ runner.os }}-xmake-${{ hashFiles('**/xmake.lua') }}
          restore-keys: |
            ${{ runner.os }}-xmake-

      - name: setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Build Project (Release)
        run: |
          xmake config --mode=release -y
          xmake build -v -y
  
      - name: Package Artifacts
        run: |
          xmake package -o release/  # 打包生成物到release目录
          ls -lh release/  # 确认打包文件存在
  
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}  # 从tag v1.0.0获取版本
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
  
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/packages/b/bitcointrader/linux/x86_64/debug/bin/*  # 上传所有tar.gz文件
          asset_name: ${{ github.ref_name }}
          asset_content_type: application/binary
