name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 当推送v开头的tag时触发

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # 新增缓存步骤（必须放在xmake安装前）
      - name: Cache Xmake Packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.xmake
            ~/.xmake/packages
          key: ${{ runner.os }}-xmake-${{ hashFiles('**/xmake.lua') }}
          restore-keys: |
            ${{ runner.os }}-xmake-

      - name: setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Build Project (Release)
        run: |
          xmake config --mode=release -y
          xmake build -v -y
  
      - name: Package Artifacts
        run: |
          xmake package -o release/  # 打包生成物到release目录
          ls -lh release/  # 确认打包文件存在
  
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./release/packages/b/bitcointrader/linux/x86_64/debug/bin/*  # 上传所有tar.gz文件
          name: BitTrader-${{ github.ref_name }}-linux-amd64
          tag_name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: true
          make_latest: true
